import type { Metadata } from 'next'
import type { ReactNode } from 'react'

import { Toaster } from '@/components/ui/toaster'

import './globals.css'

export const metadata: Metadata = {
	title: 'Compare validators by React Hook Form',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
	return (
		<html lang="en">
			<body className="bg-background text-foreground">
				{children}
				<Toaster />
			</body>
		</html>
	)
}
